--전체 클래스 조회 (페이징)
	SELECT CLAS_ID, CLAS_TITLE, CLAS_LOCATION, CLAS_SUBJECT_JEONGBO
	FROM (
	    SELECT CLAS_ID, CLAS_TITLE, CLAS_LOCATION, CLAS_SUBJECT_JEONGBO,
	           ROW_NUMBER() OVER (ORDER BY CLAS_ID DESC) AS RN
	    FROM CLASS c
	)
	WHERE RN BETWEEN 1 AND 20;
	
--페이징 할 전체 클래스 갯수 조회 (페이징을 위함)
	SELECT COUNT(*)
		FROM TMTD.CLASS;
		
--클래스 개설
	INSERT INTO TMTD.CLASS
		(CLAS_ID, CLAS_TITLE, CLAS_LOCATION,
		CLAS_STATUS, CLAS_MAGAM_GIHAN, CLAS_HUIMANG_INWON, 
		CLAS_SUEOP_NALJJA, CLAS_CHOISO_SUGANGNYO, 
		CLAS_CHOIDAE_SUGANGNYO, CLAS_SEONGBYEOL_JEHAN, CLAS_NAI_JEHAN, 
		CLAS_SUBJECT_JEONGBO,
		CLAS_CONTENT)
			VALUES(CLAS_ID_SEQ.NEXTVAL, '도커 사용법 알려주세요','1129068500',
		'모집' , TO_CHAR(CURRENT_DATE + INTERVAL '1' MONTH, 'YYYY-MM-DD'), 8,
		'2023-09-20', 20000,
		40000,'GFREE', '20:35',
		'[{"SUBJ_ID":"1000000021"}, {"SUBJ_ID":"1000000185"}, {"SUBJ_ID":"1000000034"}]',
		'잘 가르쳐주실 분 있나요');
		
-- 과목과 과목태그 생성 (회원이 새 과목으로 클래스 신청할 때 생성, 셀렉트키 사용해야함)
	INSERT INTO TMTD.SUBJECT
		(SUBJ_ID, SUBJ_TITLE, SUBJ_STUD_ID, 
		SUBJ_STATUS, SUBJ_DELFLAG, 
		SUBJ_CODE)
		VALUES
		(SUBJ_ID_SEQ.NEXTVAL, '확률과 통계', 'TMTD74',
		'A', 'N' , 
		SUBJ_CODE_SEQ.NEXTVAL);
		
	INSERT INTO TMTD.SUBJECT_TAG
		(SUTA_CODE, SUTA_TITLE)
		VALUES('353', '확률과 통계');
--참여자 추가
	INSERT INTO TMTD.CLASS_CHAMYEOJA
		(CLCH_ID, CLCH_ACCOUNT_ID, CLCH_CLAS_ID, CLCH_STATUS, CLCH_GYEOLJE_STATUS, CLCH_YEOKAL)
	VALUES(CLCH_ID_SEQ.NEXTVAL, 'TMTD56', 1000000351, 'Y' , 'N', 'M' );	

-- 과목 전체 목록 조회 (관리를 위함)
	SELECT SUBJ_TITLE, SUBJ_STUD_ID, SUBJ_STATUS, SUBJ_SUJEONGIL, SUBJ_DELFLAG, SUBJ_CODE
	FROM (
			SELECT SUBJ_TITLE, SUBJ_STUD_ID, SUBJ_STATUS, SUBJ_SUJEONGIL, SUBJ_DELFLAG, SUBJ_CODE,
			ROW_NUMBER() OVER (ORDER BY SUBJ_CODE DESC) AS RN
			FROM TMTD.SUBJECT
		)
	WHERE RN BETWEEN 1 AND 10;
	
-- 과목 전체 갯수 조회 (과목 페이징 처리를 위함)
	SELECT COUNT(*)
		FROM TMTD.SUBJECT s;
		
-- 과목 상태 변경 (승인, 반려)
	UPDATE TMTD.SUBJECT
		SET SUBJ_STATUS = 'R',
		    SUBJ_BALLYEO_SAYU = '사이트의 취지와 맞지 않습니다',
		    SUBJ_SUJEONGIL = CURRENT_DATE,
		    SUBJ_SUJEONG_SAYU = '반려 처리',
		    SUBJ_DELFLAG = 'N',
		    SUBJ_CODE = '353'
		WHERE SUBJ_ID = 1000000353;
		
-- 클래스 상태 변경 (과목을 승인또는 반려할 경우 클래스 상태 변경)
	UPDATE TMTD.CLASS
		SET CLAS_STATUS = '취소'
		WHERE JSON_EXISTS(CLAS_SUBJECT_JEONGBO, '$[*] ? (@.SUBJ_ID == "1000000353")');
	UPDATE CLASS
	SET CLAS_SUBJECT_JEONGBO = JSON_ARRAY_APPEND(
	    CLAS_SUBJECT_JEONGBO, 
	    '$', 
	    JSON_OBJECT('SUBJ_ID' VALUE 'value1', 'key2' VALUE 'value2'),
	    JSON_OBJECT('SUBJ_ID' VALUE 'value3', 'key2' VALUE 'value4')
	)
	WHERE CLAS_ID = 1000000353;