-- 파일 업로드 insertFile
INSERT INTO TMTD."FILE"
(FILE_REF_PK, FILE_ORIGIN_NAME, FILE_SAVE_NAME, FILE_REGDATE)
VALUES('', '', '', SYSDATE);

-- 파일 다운로드를 위한 조회 getFile
SELECT FILE_REF_PK, FILE_ORIGIN_NAME, FILE_SAVE_NAME
	FROM "FILE"
	WHERE FILE_REF_PK = '';

-- TDW52211 강사 상세 프로필 조회 (수정시) getMyInstrProfile
SELECT INPR_SEQ, INED_SEQ, INPR_ACCOUNT_ID, INPR_INTRO, INPR_FEE,
		INPR_SITE_YOUTUBE, INPR_SITE_WEB, INPR_SITE_MOBILE,
		INPR_SUBJECTS, INPR_SUBJECTS_MAJOR, INED_STAGE,
		INED_SCHOOL, INED_MAJOR, INED_MINOR, TO_CHAR(INED_START,'YYYY-MM-DD') AS INED_START, TO_CHAR(INED_END, 'YYYY-MM-DD') AS INED_END
FROM INSTR_PROFILE ip INNER JOIN INSTR_EDULEVEL ie
ON INPR_SEQ = INED_INPR_SEQ
WHERE INPR_ACCOUNT_ID = 'TMTD101';

-- TDW52211 강사 상세 프로필 등록 insertInstrProfile
INSERT INTO INSTR_PROFILE (INPR_SEQ, INPR_ACCOUNT_ID, INPR_INTRO, INPR_FEE,
							 INPR_SITE_YOUTUBE, INPR_SITE_WEB, INPR_SITE_MOBILE, 
							 INPR_SUBJECTS, INPR_SUBJECTS_MAJOR, INPR_REGDATE)
VALUES (INPR_SEQ.NEXTVAL , '', '', 0,
		'', '', '',
		'', '', SYSDATE);

-- insertInstrEdulevel
INSERT INTO INSTR_EDULEVEL (INED_SEQ, INED_INPR_SEQ, INED_STAGE, 
							INED_SCHOOL, INED_MAJOR, INED_MINOR, 
							INED_START, INED_END, INED_REGDATE)
VALUES (INED_SEQ.NEXTVAL, '', 0, 
		'', '', '', 
		'', '', SYSDATE);

-- TDW52211 강사 상세 프로필 수정 updateInstrProfile
UPDATE INSTR_PROFILE SET INPR_INTRO='', INPR_FEE=0, INPR_SITE_YOUTUBE='', 
							INPR_SITE_WEB='', INPR_SITE_MOBILE='', INPR_SUBJECTS='', 
							INPR_SUBJECTS_MAJOR='', INPR_REGDATE=SYSDATE
WHERE INPR_SEQ=0;

-- updateInstrEdulevel
UPDATE INSTR_EDULEVEL SET INED_STAGE=0, INED_SCHOOL='', INED_MAJOR='', 
							INED_MINOR='', INED_START='', INED_END='', INED_REGDATE=SYSDATE
WHERE INED_SEQ=0
	AND INED_INPR_SEQ = '';


-- TDW52222 경력 증명서 OCR 저장 insertCareer
INSERT INTO CAREER (CARE_ID, CARE_ACCOUNT_ID, CARE_NAME, CARE_CONTACT, 
					CARE_SOSOK, CARE_POSITION, CARE_PERIOD, 
					CARE_JOB, CARE_ISSUER, CARE_ISSUER_CONTACT, 
					CARE_DATE, CARE_COMPANY, CARE_STATUS)
VALUES ('', '', '', '', '', '', '', '', '', '', '', '', 'N');

-- (강사) 인증 요청 리스트 조회  getMyCareerList
SELECT CARE_COMPANY, CARE_SOSOK, CARE_JOB, CARE_STATUS, CARE_STATUS_DATE, CARE_REASON
FROM (
    SELECT CARE_COMPANY, CARE_SOSOK, CARE_JOB, CARE_STATUS,
           CARE_STATUS_DATE, CARE_REASON,
           ROW_NUMBER() OVER (ORDER BY CARE_STATUS_DATE DESC) AS RN
    FROM CAREER
    WHERE CARE_ACCOUNT_ID = ''
)
WHERE RN BETWEEN 1 AND 5;

-- (관리자) 인증 요청 리스트 조회 getCareerList
SELECT CARE_ID, CARE_ACCOUNT_ID, CARE_NAME, CARE_CONTACT, CARE_SOSOK,
		CARE_POSITION, CARE_PERIOD, CARE_JOB, CARE_ISSUER, CARE_ISSUER_CONTACT,
		CARE_DATE, CARE_STATUS, CARE_STATUS_DATE, CARE_REASON
	FROM CAREER c 
	WHERE CARE_STATUS = 'N'
	OR 
	CARE_ACCOUNT_ID IN (SELECT CARE_ACCOUNT_ID
						FROM CAREER c
						GROUP BY CARE_ACCOUNT_ID
						HAVING count(CARE_ACCOUNT_ID) >= 1)
   AND CARE_COMPANY IN (SELECT CARE_COMPANY
						FROM CAREER c
						GROUP BY CARE_COMPANY
						HAVING count(CARE_COMPANY) >= 1)
   AND CARE_STATUS = 'B'
   ORDER BY CARE_DATE;

-- TDW53110 경력 증명서 OCR 오류 수정 updateCareer
UPDATE CAREER SET CARE_NAME='', CARE_CONTACT='', CARE_SOSOK='', 
					CARE_POSITION='', CARE_PERIOD='', CARE_JOB='', 
					CARE_ISSUER='', CARE_ISSUER_CONTACT='', CARE_DATE='', 
					CARE_COMPANY=''
WHERE CARE_ID='TMTD101';

-- TDW53120 승인 updateCareerS
UPDATE CAREER SET CARE_STATUS = 'S', CARE_STATUS_DATE = SYSDATE WHERE CARE_ID='TMTD101';
-- updateCareerCert
UPDATE INSTR_PROFILE SET INPR_CERT = 'S'
WHERE INPR_ACCOUNT_ID = '';
-- TDW53120 반려 updateCareerB
UPDATE CAREER SET CARE_STATUS = 'B', CARE_REASON='', CARE_STATUS_DATE = SYSDATE WHERE CARE_ID='';
-- TDW53120 임시삭제 updateCareerD
UPDATE CAREER SET CARE_STATUS = 'D', CARE_STATUS_DATE = SYSDATE WHERE CARE_ID='';
-- TDW53120 완전삭제 deleteCareer
DELETE FROM CAREER WHERE CARE_ID = 'TMTD101';

-- TDW53130 완전삭제 CRON deleteCareerCron
DELETE FROM CAREER
WHERE CARE_ACCOUNT_ID IN (SELECT CARE_ACCOUNT_ID
						FROM CAREER c
						GROUP BY CARE_ACCOUNT_ID
						HAVING count(CARE_ACCOUNT_ID) >= 1)
   AND CARE_COMPANY IN (SELECT CARE_COMPANY
						FROM CAREER c
						GROUP BY CARE_COMPANY
						HAVING count(CARE_COMPANY) >= 1)
   AND CARE_STATUS = 'B'
	AND	CARE_STATUS_DATE <= SYSDATE - 10;

-- TDW55311 전체 강사 목록 조회
-- 간략프로필 조회 (전체 리스트) getAllInstr
SELECT INPR_SEQ, INPR_ACCOUNT_ID,USER_PROFILE_FILE, USER_NICKNAME, INPR_CERT,
    SUBJECTS_TITLE, SUBJECTS_MAJOR_TITLE, REVIEW_COUNT,
	CASE WHEN NTILE(10) OVER (ORDER BY INPR_LIKE_COUNT DESC) = 1 THEN 'HOT' ELSE NULL END AS INGI
FROM (
SELECT INPR_SEQ, INPR_ACCOUNT_ID, USER_PROFILE_FILE, INPR_CERT,
	    USER_NICKNAME,
	    (SELECT JSON_ARRAYAGG(s.SUTA_TITLE) 
	     FROM JSON_TABLE(INPR_SUBJECTS, '$[*]' COLUMNS (subject_code VARCHAR2(400) PATH '$')) jt
	     JOIN SUBJECT_TAG s ON jt.subject_code = s.SUTA_CODE) AS SUBJECTS_TITLE,
	    (SELECT JSON_ARRAYAGG(s.SUTA_TITLE)
	     FROM JSON_TABLE(INPR_SUBJECTS_MAJOR, '$[*]' COLUMNS (subject_code VARCHAR2(400) PATH '$')) jt
	     JOIN SUBJECT_TAG s ON jt.subject_code = s.SUTA_CODE) AS SUBJECTS_MAJOR_TITLE,
	    COUNT(REVI_CLAS_ID) AS REVIEW_COUNT, INPR_LIKE_COUNT, INPR_VIEW_COUNT, USER_JOIN_DATE
FROM INSTR_PROFILE 
JOIN USER_PROFILE ON INPR_ACCOUNT_ID = USER_ACCOUNT_ID
LEFT JOIN CLASS ON INPR_ACCOUNT_ID = CLAS_ACCOUNT_ID
LEFT JOIN REVIEW ON CLAS_ID = REVI_CLAS_ID
GROUP BY USER_PROFILE_FILE, USER_NICKNAME, INPR_SUBJECTS, INPR_SUBJECTS_MAJOR, INPR_LIKE_COUNT, INPR_ACCOUNT_ID, INPR_CERT, INPR_VIEW_COUNT, USER_JOIN_DATE,INPR_SEQ
)
ORDER BY INPR_LIKE_COUNT DESC;

SELECT *
	FROM SUBJECT_TAG;
-- 다이나믹 쿼리
ORDER BY INPR_VIEW_COUNT DESC;
ORDER BY USER_JOIN_DATE DESC;

-- CRON으로 하루한번 REGDATE UPDATE? OR 좋아요, 조회수 바뀔때마다 REGDATE도 같이 UPDATE?


-- TDW55312 logstash에 넣을 쿼리문 
SELECT INPR_SEQ, INPR_ACCOUNT_ID,USER_PROFILE_FILE, USER_NICKNAME, INPR_CERT,
    SUBJECTS_TITLE, SUBJECTS_MAJOR_TITLE, REVIEW_COUNT,
    INPR_SUBJECTS, INPR_SUBJECTS_MAJOR, INPR_LIKE_COUNT, 
    INPR_VIEW_COUNT, INPR_REGDATE,
	CASE WHEN NTILE(10) OVER (ORDER BY INPR_LIKE_COUNT DESC) = 1 THEN 'HOT' ELSE NULL END AS INGI
FROM (
SELECT INPR_ACCOUNT_ID, up.USER_PROFILE_FILE, INPR_CERT, INPR_SEQ,
	    up.USER_NICKNAME,
	    (SELECT JSON_ARRAYAGG(s.SUTA_TITLE) 
	     FROM JSON_TABLE(ip.INPR_SUBJECTS, '$[*]' COLUMNS (subject_code VARCHAR2(400) PATH '$')) jt
	     JOIN SUBJECT_TAG s ON jt.subject_code = s.SUTA_CODE) AS SUBJECTS_TITLE,
	    (SELECT JSON_ARRAYAGG(s.SUTA_TITLE)
	     FROM JSON_TABLE(ip.INPR_SUBJECTS_MAJOR, '$[*]' COLUMNS (subject_code VARCHAR2(400) PATH '$')) jt
	     JOIN SUBJECT_TAG s ON jt.subject_code = s.SUTA_CODE) AS SUBJECTS_MAJOR_TITLE,
	    COUNT(r.REVI_CLAS_ID) AS REVIEW_COUNT,
	    INPR_SUBJECTS, INPR_SUBJECTS_MAJOR, INPR_LIKE_COUNT, INPR_VIEW_COUNT, INPR_REGDATE
FROM INSTR_PROFILE ip 
JOIN USER_PROFILE up ON ip.INPR_ACCOUNT_ID = up.USER_ACCOUNT_ID
LEFT JOIN CLASS c ON ip.INPR_ACCOUNT_ID = c.CLAS_ACCOUNT_ID
LEFT JOIN REVIEW r ON c.CLAS_ID = r.REVI_CLAS_ID
GROUP BY up.USER_PROFILE_FILE, up.USER_NICKNAME, ip.INPR_SUBJECTS, ip.INPR_SUBJECTS_MAJOR, ip.INPR_LIKE_COUNT, INPR_ACCOUNT_ID, INPR_VIEW_COUNT, INPR_REGDATE, INPR_CERT, INPR_SEQ
)
WHERE INPR_REGDATE > :sql_last_value;

-- TDW55320 강사 상세 프로필 조회
-- 좋아요 누를때 UPDATE updateInstrLike
UPDATE INSTR_PROFILE SET INPR_LIKE = '', INPR_LIKE_COUNT = 0, INPR_REGDATE = SYSDATE
	WHERE INPR_SEQ = '';
-- 조회수 누를때 UPDATE updateInstrView
UPDATE INSTR_PROFILE SET INPR_VIEW = '', INPR_VIEW_COUNT = 0, INPR_REGDATE = SYSDATE
	WHERE INPR_SEQ = '';

-- 간략프로필 getOneInstrSimple
SELECT INPR_SEQ, INPR_ACCOUNT_ID, INPR_INTRO, USER_NICKNAME, USER_PROFILE_FILE, INPR_CERT, INPR_LIKE,
		(SELECT JSON_ARRAYAGG(s.SUTA_TITLE) 
	     FROM JSON_TABLE(INPR_SUBJECTS, '$[*]' COLUMNS (subject_code VARCHAR2(400) PATH '$')) jt
	     JOIN SUBJECT_TAG s ON jt.subject_code = s.SUTA_CODE) AS SUBJECTS_TITLE,
	     INPR_SITE_YOUTUBE, INPR_SITE_WEB, INPR_SITE_MOBILE
	FROM INSTR_PROFILE JOIN USER_PROFILE
	ON INPR_ACCOUNT_ID = USER_ACCOUNT_ID
	WHERE INPR_ACCOUNT_ID = 'TMTD101';

-- TDW55323 (탭)상세프로필 getOneInstrProfile
SELECT (SELECT JSON_ARRAYAGG(s.SUTA_TITLE)
	     FROM JSON_TABLE(INPR_SUBJECTS_MAJOR, '$[*]' COLUMNS (subject_code VARCHAR2(400) PATH '$')) jt
	     JOIN SUBJECT_TAG s ON jt.subject_code = s.SUTA_CODE) AS SUBJECTS_MAJOR_TITLE,
	     INPR_FEE, INED_SCHOOL, INED_MAJOR, INED_MINOR,
	     TO_CHAR(INED_START, 'YYYY-MM-DD') AS INED_START, TO_CHAR(INED_END, 'YYYY-MM-DD') AS INED_END
	FROM INSTR_PROFILE JOIN INSTR_EDULEVEL
	ON INPR_SEQ = INED_INPR_SEQ
	WHERE INPR_ACCOUNT_ID = 'TMTD101';

-- TDW55324 (탭) 경력사항 getOneInstrCareer
SELECT CARE_ACCOUNT_ID, CARE_COMPANY, CARE_JOB, CARE_PERIOD
	FROM CAREER c 
	WHERE CARE_STATUS = 'S' OR CARE_STATUS = 'D'
		AND CARE_ACCOUNT_ID = '';

-- TDW55325 (탭) 클래스 이력 getOneInstrClass
SELECT CLAS_ID, CLAS_TITLE, CLAS_LOCATION, CLAS_SUEOP_NALJJA, CLAS_SUGANGNYO,
		(SELECT JSON_ARRAYAGG(s.SUTA_TITLE)
	     FROM JSON_TABLE(CLAS_SUBJECT_JEONGBO, '$[*]' COLUMNS (subject_code VARCHAR2(400) PATH '$')) jt
	     JOIN SUBJECT_TAG s ON jt.subject_code = s.SUTA_CODE) AS CLAS_SUBJECT_JEONGBO
	FROM CLASS JOIN INSTR_PROFILE
	ON CLAS_ACCOUNT_ID = INPR_ACCOUNT_ID
	WHERE CLAS_STATUS = '종료'
	AND INPR_ACCOUNT_ID = 'TMTD101';

-- TDW55326 (탭) 후기 이력 getOneIntrReview
SELECT CLAS_TITLE, REVI_STUD_NAME, REVI_PRO, REVI_PREPARE,
		(REVI_PRO + REVI_PREPARE + REVI_ABIL + REVI_SIGAN) / 4.0 AS AVG_SCORE,
		REVI_ABIL, REVI_SIGAN, REVI_DETAIL, REVI_REGDATE
	FROM REVIEW JOIN CLASS
	ON CLAS_ID = REVI_CLAS_ID
	WHERE CLAS_ACCOUNT_ID = ''
	ORDER BY REVI_REGDATE DESC;
--다이나믹 쿼리
ORDER BY AVG_SCORE DESC;
ORDER BY AVG_SCORE ASC;


-- 후기 리스트 getMyReview
SELECT REVI_SEQ, CLAS_TITLE, REVI_STUD_NAME, REVI_PRO, REVI_PREPARE,
		(REVI_PRO + REVI_PREPARE + REVI_ABIL + REVI_SIGAN) / 4.0 AS AVG_SCORE,
		REVI_ABIL, REVI_SIGAN, REVI_DETAIL, REVI_REGDATE
	FROM REVIEW JOIN CLASS
	ON CLAS_ID = REVI_CLAS_ID
	WHERE CLAS_ACCOUNT_ID = '';

-- 후기 작성 insertReview
-- 가져와야될 값 CLAS_ID, USER_NICKNAME(학생) 
INSERT INTO REVIEW (REVI_SEQ, REVI_CLAS_ID, REVI_STUD_NAME, 
					REVI_PRO, REVI_PREPARE, REVI_ABIL, 
					REVI_SIGAN, REVI_DETAIL, REVI_REGDATE)
VALUES (REVI_SEQ.NEXTVAL, 1000000071, '', 
		0, 0, 0, 
		0, '', SYSDATE);

-- 후기 삭제 deleteReview
DELETE FROM REVIEW
WHERE REVI_SEQ IN ('','');



