SELECT MAX(GAYE_ID)
	FROM GANGEUISIL_YEYAK;
SELECT CLCH_ACCOUNT_ID 
	FROM CLASS_CHAMYEOJA
	WHERE CLCH_CLAS_ID =1000000013
		AND CLCH_STATUS = 'Y'
		AND NOT CLCH_YEOKAL = 'I';
SELECT GAYE_GYEOLJE_USER 
	FROM GANGEUISIL_YEYAK
	WHERE GAYE_ID = (SELECT MAX(GAYE_ID) FROM GANGEUISIL_YEYAK);