-- GANGEUISIL_COMM(강의실 공통 정보)
DROP TABLE SAKJE_COMMUNITY_REPLY;
DROP SEQUENCE COMMUNITY_REPLY_SEQ;
DROP TABLE COMMUNITY_REPLY;
DROP TABLE JAYU_BOARD;
DROP TABLE JILMUN_BOARD;
DROP SEQUENCE PILGI_IMSIJEOJANG_SEQ;
DROP TABLE PILGI_IMSIJEOJANG;
DROP TABLE PILGI_BOARD;
DROP SEQUENCE SINGO_USER_SEQ;
DROP TABLE SINGO_USER;
DROP SEQUENCE SINGO_SAYU_SEQ;
DROP TABLE SINGO_SAYU;
DROP TABLE SINGO_DAESANG;
DROP TABLE SINGO_CATEGORY;
DROP TABLE GANGEUISIL_YEYAK;
DROP TABLE GANGEUISIL_GAEBYEOL;
DROP TABLE GANGEUISIL_COMM;