SELECT *
	FROM USER_PROFILE up 
		WHERE USER_EMAIL ='wjddns7828@naver.com';


-- 일반 회원가입 쿼리
INSERT INTO WOON.USER_PROFILE
		(USER_ACCOUNT_ID, 
		USER_EMAIL, USER_PASSWORD, USER_NAME,
		USER_NICKNAME, 
		USER_AUTH, USER_PHONE_NUMBER, USER_AUTO_LOGIN_TOKEN, 
		USER_JOIN_DATE, USER_LAST_ACCESS_DATE, USER_GENDER, 
		USER_SITE, USER_BIRTH, USER_PROFILE_FILE, USER_DELFLAG)
	VALUES((SELECT 'TMTD'|| ID  AS USER_ACCOUNT_ID 
			FROM(SELECT MAX(CAST(REPLACE(ID,'TMTD') AS NUMBER))+1 AS ID 
					FROM(SELECT USER_ACCOUNT_ID  AS ID 	FROM
							(SELECT USER_ACCOUNT_ID FROM USER_PROFILE up 
								UNION 
							SELECT USER_ACCOUNT_ID FROM NAVER_USER_PROFILE nup 
								UNION 
							SELECT USER_ACCOUNT_ID FROM KAKAO_USER_PROFILE kup 
								UNION 
							SELECT USER_ACCOUNT_ID FROM GOOGLE_USER_PROFILE gup)))),
			'wjddns7828@naver.com', 'qwer1234','임정운',
			(SELECT '타문타답'|| ID  AS USER_ACCOUNT_ID 
				FROM(
					SELECT MAX(CAST(REPLACE(ID,'TMTD') AS NUMBER))+1 AS ID 
						FROM(SELECT USER_ACCOUNT_ID  AS ID 
							FROM(SELECT USER_ACCOUNT_ID FROM USER_PROFILE up 
									UNION 
								SELECT USER_ACCOUNT_ID FROM NAVER_USER_PROFILE nup 
									UNION 
								SELECT USER_ACCOUNT_ID FROM KAKAO_USER_PROFILE kup 
									UNION 
								SELECT USER_ACCOUNT_ID FROM GOOGLE_USER_PROFILE gup)))),
			'S','01066389809', 'AUTOLOGIN12345',
			SYSDATE,SYSDATE , 'M', 
			'T', '19980902', '기본경로 잡아주기' , 'N' );
		
-- 네이버 회원가입 쿼리
INSERT INTO NAVER_USER_PROFILE nup2
		(USER_ACCOUNT_ID,
		USER_EMAIL, USER_REFRESH_TOKEN,	USER_NAME, 
		USER_NICKNAME, 
		USER_JOIN_DATE, USER_LAST_ACCESS_DATE, USER_GENDER, 
		USER_BIRTH, USER_PHONE_NUMBER, USER_SITE, 
		USER_DELFLAG, USER_PROFILE_FILE, USER_AUTH)
		VALUES((SELECT 'TMTD'|| ID  AS USER_ACCOUNT_ID 
			FROM(SELECT MAX(CAST(REPLACE(ID,'TMTD') AS NUMBER))+1 AS ID 
					FROM(SELECT USER_ACCOUNT_ID  AS ID 	
						FROM(SELECT USER_ACCOUNT_ID FROM USER_PROFILE up 
								UNION 
							SELECT USER_ACCOUNT_ID FROM NAVER_USER_PROFILE nup 
								UNION 
							SELECT USER_ACCOUNT_ID FROM KAKAO_USER_PROFILE kup 
								UNION 
							SELECT USER_ACCOUNT_ID FROM GOOGLE_USER_PROFILE gup)))),
				'wjddns7828@naver', '1234', '임정운', 
				(SELECT '네이버'|| ID  AS USER_ACCOUNT_ID 
					FROM(SELECT MAX(CAST(REPLACE(ID,'TMTD') AS NUMBER))+1 AS ID 
							FROM(SELECT USER_ACCOUNT_ID  AS ID 	FROM
									(SELECT USER_ACCOUNT_ID FROM USER_PROFILE up 
										UNION 
									SELECT USER_ACCOUNT_ID FROM NAVER_USER_PROFILE nup 
										UNION 
									SELECT USER_ACCOUNT_ID FROM KAKAO_USER_PROFILE kup 
										UNION 
									SELECT USER_ACCOUNT_ID FROM GOOGLE_USER_PROFILE gup)))),
				SYSDATE , SYSDATE , 'M', 
				'19980902', '0106638', 'K' , 
				'N' , 'ㅁㄴㅇ', 'S');
			
-- 카카오 회원가입 쿼리
INSERT INTO KAKAO_USER_PROFILE kup2 
		(USER_ACCOUNT_ID,
		USER_EMAIL, USER_REFRESH_TOKEN,	USER_NAME, 
		USER_NICKNAME, 
		USER_JOIN_DATE, USER_LAST_ACCESS_DATE, USER_GENDER, 
		USER_BIRTH, USER_PHONE_NUMBER, USER_SITE, 
		USER_DELFLAG, USER_PROFILE_FILE, USER_AUTH)
		VALUES((SELECT 'TMTD'|| ID  AS USER_ACCOUNT_ID 
			FROM(SELECT MAX(CAST(REPLACE(ID,'TMTD') AS NUMBER))+1 AS ID 
					FROM(SELECT USER_ACCOUNT_ID  AS ID 	
						FROM(SELECT USER_ACCOUNT_ID FROM USER_PROFILE up 
								UNION 
							SELECT USER_ACCOUNT_ID FROM NAVER_USER_PROFILE nup 
								UNION 
							SELECT USER_ACCOUNT_ID FROM KAKAO_USER_PROFILE kup 
								UNION 
							SELECT USER_ACCOUNT_ID FROM GOOGLE_USER_PROFILE gup)))),
				'wjddns7828@naver', '1234', '임정운', 
				(SELECT '카카오'|| ID  AS USER_ACCOUNT_ID 
					FROM(SELECT MAX(CAST(REPLACE(ID,'TMTD') AS NUMBER))+1 AS ID 
							FROM(SELECT USER_ACCOUNT_ID  AS ID 	FROM
									(SELECT USER_ACCOUNT_ID FROM USER_PROFILE up 
										UNION 
									SELECT USER_ACCOUNT_ID FROM NAVER_USER_PROFILE nup 
										UNION 
									SELECT USER_ACCOUNT_ID FROM KAKAO_USER_PROFILE kup 
										UNION 
									SELECT USER_ACCOUNT_ID FROM GOOGLE_USER_PROFILE gup)))),
				SYSDATE , SYSDATE , 'M', 
				'19980902', '0106638', 'K' , 
				'N' , 'ㅁㄴㅇ', 'S');
			
-- 구글 회원가입 쿼리
INSERT INTO GOOGLE_USER_PROFILE gup2 
		(USER_ACCOUNT_ID,
		USER_EMAIL, USER_REFRESH_TOKEN,	USER_NAME, 
		USER_NICKNAME, 
		USER_JOIN_DATE, USER_LAST_ACCESS_DATE, USER_GENDER, 
		USER_BIRTH, USER_PHONE_NUMBER, USER_SITE, 
		USER_DELFLAG, USER_PROFILE_FILE, USER_AUTH)
		VALUES((SELECT 'TMTD'|| ID  AS USER_ACCOUNT_ID 
			FROM(SELECT MAX(CAST(REPLACE(ID,'TMTD') AS NUMBER))+1 AS ID 
					FROM(SELECT USER_ACCOUNT_ID  AS ID 	
						FROM(SELECT USER_ACCOUNT_ID FROM USER_PROFILE up 
								UNION 
							SELECT USER_ACCOUNT_ID FROM NAVER_USER_PROFILE nup 
								UNION 
							SELECT USER_ACCOUNT_ID FROM KAKAO_USER_PROFILE kup 
								UNION 
							SELECT USER_ACCOUNT_ID FROM GOOGLE_USER_PROFILE gup)))),
				'wjddns7828@naver', '1234', '임정운', 
				(SELECT '구글'|| ID  AS USER_ACCOUNT_ID 
					FROM(SELECT MAX(CAST(REPLACE(ID,'TMTD') AS NUMBER))+1 AS ID 
							FROM(SELECT USER_ACCOUNT_ID  AS ID 	FROM
									(SELECT USER_ACCOUNT_ID FROM USER_PROFILE up 
										UNION 
									SELECT USER_ACCOUNT_ID FROM NAVER_USER_PROFILE nup 
										UNION 
									SELECT USER_ACCOUNT_ID FROM KAKAO_USER_PROFILE kup 
										UNION 
									SELECT USER_ACCOUNT_ID FROM GOOGLE_USER_PROFILE gup)))),
				SYSDATE , SYSDATE , 'M', 
				'19980902', '01066389809', 'K' , 
				'N' , 'ㅁㄴㅇ', 'S');

--이메일 중복 확인 쿼리
	SELECT 
		CASE WHEN COUNT(*) > 0  THEN 'TRUE' ELSE 'FALSE' END
			FROM USER_PROFILE up 
				WHERE USER_EMAIL ='wjddns7828@naver.com';

--닉네임 변경 전 중복 된 닉네임 확인 쿼리
SELECT 
	CASE WHEN COUNT(*) > 0 THEN 'TRUE' ELSE 'FALSE' END
	FROM(
		SELECT USER_NICKNAME 
			FROM USER_PROFILE up 
		UNION
		SELECT USER_NICKNAME 
			FROM KAKAO_USER_PROFILE kup 
		UNION
		SELECT USER_NICKNAME 
			FROM NAVER_USER_PROFILE nup 
		UNION
		SELECT USER_NICKNAME 
			FROM GOOGLE_USER_PROFILE gup ) 
	WHERE USER_NICKNAME = '카카오200';
			
--닉네임 변경 쿼리
UPDATE USER_PROFILE SET USER_NICKNAME = '1234'
	WHERE USER_EMAIL = 'wjddns7828@naver.com';

--핸드폰 중복 확인
SELECT 
	CASE WHEN COUNT(*) > 0 THEN 'TRUE' ELSE 'FALSE' END
	FROM USER_PROFILE up 
		WHERE USER_PHONE_NUMBER ='01066389809';
		
--일반 로그인
SELECT USER_ACCOUNT_ID, USER_EMAIL, USER_NAME, USER_NICKNAME, USER_AUTH, USER_PHONE_NUMBER, USER_AUTO_LOGIN_TOKEN, USER_GENDER, USER_SITE,
	'<img id=profile_img src='''||USER_PROFILE_FILE ||''' alt='''||USER_NICKNAME||'님의 프로필사진''></img>' AS USER_PROFILE_FILE 
	FROM USER_PROFILE up 
	WHERE USER_EMAIL ='wjddns7828@naver.com'
	AND USER_PASSWORD ='qwer1234';

--로그인시 최근 접속시간 최근 접속시간 수정 쿼리
UPDATE USER_PROFILE SET USER_LAST_ACCESS_DATE = SYSDATE
	WHERE USER_ACCOUNT_ID = 'TMTD194';

-- 카카오소셜 로그인
SELECT USER_ACCOUNT_ID , USER_EMAIL, USER_NAME, USER_NICKNAME, USER_AUTH, USER_PHONE_NUMBER, USER_REFRESH_TOKEN, USER_GENDER, USER_SITE,
	'<img id=profile_img src='''||USER_PROFILE_FILE ||''' alt='''||USER_NICKNAME||'님의 프로필사진''></img>' AS USER_PROFILE_FILE 
	FROM KAKAO_USER_PROFILE 
	WHERE USER_EMAIL ='wjddns7828@naver';

-- 카카오소셜 로그인 최근 접속시간 수정 쿼리
UPDATE KAKAO_USER_PROFILE  SET USER_LAST_ACCESS_DATE = SYSDATE
	WHERE USER_ACCOUNT_ID = 'TMTD192';

-- 구글 소셜 로그인
SELECT USER_ACCOUNT_ID , USER_EMAIL, USER_NAME, USER_NICKNAME, USER_AUTH, USER_PHONE_NUMBER, USER_REFRESH_TOKEN, USER_GENDER, USER_SITE,
	'<img id=profile_img src='''||USER_PROFILE_FILE ||''' alt='''||USER_NICKNAME||'님의 프로필사진''></img>' AS USER_PROFILE_FILE 
	FROM GOOGLE_USER_PROFILE 
	WHERE USER_EMAIL ='wjddns7828@naver';

-- 구글 소셜 로그인 최근 접속시간 수정 쿼리
UPDATE GOOGLE_USER_PROFILE  SET USER_LAST_ACCESS_DATE = SYSDATE
	WHERE USER_ACCOUNT_ID = 'TMTD193';

-- 네이버소셜 로그인
SELECT USER_ACCOUNT_ID , USER_EMAIL, USER_NAME, USER_NICKNAME, USER_AUTH, USER_PHONE_NUMBER, USER_REFRESH_TOKEN, USER_GENDER, USER_SITE,
	'<img id=profile_img src='''||USER_PROFILE_FILE ||''' alt='''||USER_NICKNAME||'님의 프로필사진''></img>' AS USER_PROFILE_FILE 
	FROM NAVER_USER_PROFILE 
	WHERE USER_EMAIL ='wjddns7828@naver';

-- 네이버소셜 로그인 최근 접속시간 수정 쿼리
UPDATE NAVER_USER_PROFILE  SET USER_LAST_ACCESS_DATE = SYSDATE
	WHERE USER_ACCOUNT_ID = 'TMTD191';
	
-- 관리자 계정 등록
INSERT INTO ADMIN_PROFILE ap (ADPR_ID,ADPR_PASSWORD, ADPR_NAME, ADPR_ACCESS_IP, ADPR_AUTH)
	VALUES('testadmin1234','asd123','어드민 계정생성 테스트', '테스트IP','T');
	
--관리자 계정 비밀번호 초기화
UPDATE ADMIN_PROFILE SET ADPR_LAST_ACCESS = NULL
	WHERE ADPR_ID ='testadmin1234';

--관리자 접속 시 최근 접속시간 설정
UPDATE ADMIN_PROFILE SET ADPR_LAST_ACCESS = SYSDATE 
	WHERE ADPR_ID = 'testadmin1234';

--관리자 비밀번호 설정
UPDATE ADMIN_PROFILE SET ADPR_PASSWORD = '1234'
	WHERE ADPR_ID = 'testadmin1234';

--관리자 로그인
SELECT ADPR_ID , ADPR_PASSWORD , ADPR_NAME , ADPR_AUTH 
	FROM ADMIN_PROFILE ap 
		WHERE ADPR_ID ='testadmin1234'
			AND ADPR_PASSWORD ='1234'
			AND ADPR_ACCESS_IP = '테스트IP'
			AND ADPR_DELFLAG ='N';


















